[package]
name = "serial-echo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vex-sdk = "0.17.0"
vexide = { git = "https://github.com/vexide/vexide.git", version = "0.3.0" }
